const DemosMenuTypes = {
  DEMO_MOVE_UP: 'DEMO_MOVE_UP',
  DEMO_MOVE_DOWN: 'DEMO_MOVE_DOWN',
  DEMO_MOVE_LEFT: 'DEMO_MOVE_LEFT',
  DEMO_MOVE_RIGHT: 'DEMO_MOVE_RIGHT',
  DEMO_SELECT: 'DEMO_SELECT'
};

export default DemosMenuTypes;
